# Generated by Django 5.2.5 on 2025-08-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
