# Generated by Django 5.2.5 on 2026-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_address_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customisation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('box', 'Cookie Box'), ('classic', 'Classic Cookie'), ('limited', 'Limited Cookie')], default='box', max_length=20),
        ),
    ]
