# Generated by Django 5.2.5 on 2026-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customer_address_customer_city_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customisation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
