# Generated by Django 5.2.5 on 2026-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orderitem_customisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('collection', 'Collection')], default='delivery', max_length=20),
        ),
    ]
